-- EHR-CDSS Database Schema
-- Compatible with SQLite 3.x
-- Applied automatically at startup via DatabaseManager::applySchema()

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- -------------------------------------------------------------------------
-- Patients
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Patients (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    firstName  TEXT NOT NULL,
    lastName   TEXT NOT NULL,
    dob        TEXT NOT NULL,           -- ISO 8601 date: YYYY-MM-DD
    gender     TEXT NOT NULL,           -- male | female | other | unknown
    mrn        TEXT UNIQUE NOT NULL     -- Medical Record Number
);

-- -------------------------------------------------------------------------
-- Encounters
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Encounters (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    patientId   INTEGER NOT NULL REFERENCES Patients(id) ON DELETE CASCADE,
    type        TEXT NOT NULL,          -- outpatient | inpatient | emergency
    reason      TEXT,
    providerId  TEXT,
    notes       TEXT,
    date        INTEGER NOT NULL        -- Unix timestamp
);

-- -------------------------------------------------------------------------
-- Observations  (vital signs, lab results, etc.)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Observations (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    encounterId  INTEGER NOT NULL REFERENCES Encounters(id) ON DELETE CASCADE,
    code         TEXT NOT NULL,         -- LOINC or local code
    description  TEXT,
    value        TEXT NOT NULL,
    unit         TEXT,
    recordedAt   INTEGER NOT NULL       -- Unix timestamp
);

-- -------------------------------------------------------------------------
-- Medications
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS Medications (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    patientId   INTEGER NOT NULL REFERENCES Patients(id) ON DELETE CASCADE,
    rxCode      TEXT NOT NULL,          -- RxNorm or local code
    name        TEXT NOT NULL,
    dosage      TEXT,
    frequency   TEXT,
    route       TEXT,
    status      TEXT DEFAULT 'active',  -- active | stopped | completed
    startDate   INTEGER NOT NULL,       -- Unix timestamp
    endDate     INTEGER                 -- Unix timestamp (NULL if ongoing)
);

-- -------------------------------------------------------------------------
-- Clinical Alerts  (generated by CDSS inference engine)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ClinicalAlerts (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    patientId   INTEGER NOT NULL REFERENCES Patients(id) ON DELETE CASCADE,
    alertType   TEXT NOT NULL,          -- risk | contraindication | recommendation
    description TEXT NOT NULL,
    severity    TEXT NOT NULL,          -- low | medium | high | critical
    createdAt   INTEGER NOT NULL        -- Unix timestamp
);
